name: Build C++ Project

on:
  push:
    branches:
      - BranchMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: |
          make
